# This file has been generated by node2nix 1.6.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, globalBuildInputs ? []}:

let
  sources = {
    "amqplib-0.5.2" = {
      name = "amqplib";
      packageName = "amqplib";
      version = "0.5.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/amqplib/-/amqplib-0.5.2.tgz";
        sha512 = "l9mCs6LbydtHqRniRwYkKdqxVa6XMz3Vw1fh+2gJaaVgTM6Jk3o8RccAKWKtlhT1US5sWrFh+KKxsVUALURSIA==";
      };
    };
    "async-2.6.1" = {
      name = "async";
      packageName = "async";
      version = "2.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/async/-/async-2.6.1.tgz";
        sha512 = "fNEiL2+AZt6AlAw/29Cr0UDe4sRAHCpEHh54WMz+Bb7QfNcFw4h3loofyJpLeQs4Yx7yuqu/2dLgM5hKOs6HlQ==";
      };
    };
    "base64-url-1.3.3" = {
      name = "base64-url";
      packageName = "base64-url";
      version = "1.3.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/base64-url/-/base64-url-1.3.3.tgz";
        sha1 = "f8b6c537f09a4fc58c99cb86e0b0e9c61461a20f";
      };
    };
    "bitsyntax-0.0.4" = {
      name = "bitsyntax";
      packageName = "bitsyntax";
      version = "0.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/bitsyntax/-/bitsyntax-0.0.4.tgz";
        sha1 = "eb10cc6f82b8c490e3e85698f07e83d46e0cba82";
      };
    };
    "bluebird-2.11.0" = {
      name = "bluebird";
      packageName = "bluebird";
      version = "2.11.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/bluebird/-/bluebird-2.11.0.tgz";
        sha1 = "534b9033c022c9579c56ba3b3e5a5caafbb650e1";
      };
    };
    "bluebird-3.5.1" = {
      name = "bluebird";
      packageName = "bluebird";
      version = "3.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/bluebird/-/bluebird-3.5.1.tgz";
        sha512 = "MKiLiV+I1AA596t9w1sQJ8jkiSr5+ZKi0WKrYGUn6d1Fx+Ij4tIj+m2WMQSGczs5jZVxV339chE8iwk6F64wjA==";
      };
    };
    "buffer-more-ints-0.0.2" = {
      name = "buffer-more-ints";
      packageName = "buffer-more-ints";
      version = "0.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/buffer-more-ints/-/buffer-more-ints-0.0.2.tgz";
        sha1 = "26b3885d10fa13db7fc01aae3aab870199e0124c";
      };
    };
    "color-3.0.0" = {
      name = "color";
      packageName = "color";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/color/-/color-3.0.0.tgz";
        sha512 = "jCpd5+s0s0t7p3pHQKpnJ0TpQKKdleP71LWcA0aqiljpiuAkOSUFN/dyH8ZwF0hRmFlrIuRhufds1QyEP9EB+w==";
      };
    };
    "color-convert-1.9.2" = {
      name = "color-convert";
      packageName = "color-convert";
      version = "1.9.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/color-convert/-/color-convert-1.9.2.tgz";
        sha512 = "3NUJZdhMhcdPn8vJ9v2UQJoH0qqoGUkYTgFEPZaPjEtwmmKUfNV46zZmgB2M5M4DCEQHMaCfWHCxiBflLm04Tg==";
      };
    };
    "color-name-1.1.1" = {
      name = "color-name";
      packageName = "color-name";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/color-name/-/color-name-1.1.1.tgz";
        sha1 = "4b1415304cf50028ea81643643bd82ea05803689";
      };
    };
    "color-string-1.5.3" = {
      name = "color-string";
      packageName = "color-string";
      version = "1.5.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/color-string/-/color-string-1.5.3.tgz";
        sha512 = "dC2C5qeWoYkxki5UAXapdjqO672AM4vZuPGRQfO8b5HKuKGBbKWpITyDYN7TOFKvRW7kOgAn3746clDBMDJyQw==";
      };
    };
    "colornames-1.1.1" = {
      name = "colornames";
      packageName = "colornames";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/colornames/-/colornames-1.1.1.tgz";
        sha1 = "f8889030685c7c4ff9e2a559f5077eb76a816f96";
      };
    };
    "colors-1.3.1" = {
      name = "colors";
      packageName = "colors";
      version = "1.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/colors/-/colors-1.3.1.tgz";
        sha512 = "jg/vxRmv430jixZrC+La5kMbUWqIg32/JsYNZb94+JEmzceYbWKTsv1OuTp+7EaqiaWRR2tPcykibwCRgclIsw==";
      };
    };
    "colorspace-1.1.1" = {
      name = "colorspace";
      packageName = "colorspace";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/colorspace/-/colorspace-1.1.1.tgz";
        sha512 = "pI3btWyiuz7Ken0BWh9Elzsmv2bM9AhA7psXib4anUXy/orfZ/E0MbQwhSOG/9L8hLlalqrU0UhOuqxW1YjmVw==";
      };
    };
    "core-util-is-1.0.2" = {
      name = "core-util-is";
      packageName = "core-util-is";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/core-util-is/-/core-util-is-1.0.2.tgz";
        sha1 = "b5fd54220aa2bc5ab57aab7140c940754503c1a7";
      };
    };
    "diagnostics-1.1.1" = {
      name = "diagnostics";
      packageName = "diagnostics";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/diagnostics/-/diagnostics-1.1.1.tgz";
        sha512 = "8wn1PmdunLJ9Tqbx+Fx/ZEuHfJf4NKSN2ZBj7SJC/OWRWha843+WsTjqMe1B5E3p28jqBlp+mJ2fPVxPyNgYKQ==";
      };
    };
    "enabled-1.0.2" = {
      name = "enabled";
      packageName = "enabled";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/enabled/-/enabled-1.0.2.tgz";
        sha1 = "965f6513d2c2d1c5f4652b64a2e3396467fc2f93";
      };
    };
    "env-variable-0.0.4" = {
      name = "env-variable";
      packageName = "env-variable";
      version = "0.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/env-variable/-/env-variable-0.0.4.tgz";
        sha512 = "+jpGxSWG4vr6gVxUHOc4p+ilPnql7NzZxOZBxNldsKGjCF+97df3CbuX7XMaDa5oAVkKQj4rKp38rYdC4VcpDg==";
      };
    };
    "fast-safe-stringify-2.0.5" = {
      name = "fast-safe-stringify";
      packageName = "fast-safe-stringify";
      version = "2.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/fast-safe-stringify/-/fast-safe-stringify-2.0.5.tgz";
        sha512 = "QHbbCj2PmRSMNL9P7EuNBCeNXO06/E3t3XyQgb32AZul8wLmRa1Wbt2cm7GeUsX9OZGyXTQxMYcPOEBqARyhNw==";
      };
    };
    "fecha-2.3.3" = {
      name = "fecha";
      packageName = "fecha";
      version = "2.3.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/fecha/-/fecha-2.3.3.tgz";
        sha512 = "lUGBnIamTAwk4znq5BcqsDaxSmZ9nDVJaij6NvRt/Tg4R69gERA+otPKbS86ROw9nxVMw2/mp1fnaiWqbs6Sdg==";
      };
    };
    "inherits-2.0.3" = {
      name = "inherits";
      packageName = "inherits";
      version = "2.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/inherits/-/inherits-2.0.3.tgz";
        sha1 = "633c2c83e3da42a502f52466022480f4208261de";
      };
    };
    "is-arrayish-0.3.2" = {
      name = "is-arrayish";
      packageName = "is-arrayish";
      version = "0.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-arrayish/-/is-arrayish-0.3.2.tgz";
        sha512 = "eVRqCvVlZbuw3GrM63ovNSNAeA1K16kaR/LRY/92w0zxQ5/1YzwblUX652i4Xs9RwAGjW9d9y6X88t8OaAJfWQ==";
      };
    };
    "is-stream-1.1.0" = {
      name = "is-stream";
      packageName = "is-stream";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-stream/-/is-stream-1.1.0.tgz";
        sha1 = "12d4a3dd4e68e0b79ceb8dbc84173ae80d91ca44";
      };
    };
    "isarray-0.0.1" = {
      name = "isarray";
      packageName = "isarray";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/isarray/-/isarray-0.0.1.tgz";
        sha1 = "8a18acfca9a8f4177e09abfc6038939b05d1eedf";
      };
    };
    "isarray-1.0.0" = {
      name = "isarray";
      packageName = "isarray";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/isarray/-/isarray-1.0.0.tgz";
        sha1 = "bb935d48582cba168c06834957a54a3e07124f11";
      };
    };
    "kuler-1.0.0" = {
      name = "kuler";
      packageName = "kuler";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/kuler/-/kuler-1.0.0.tgz";
        sha512 = "oyy6pu/yWRjiVfCoJebNUKFL061sNtrs9ejKTbirIwY3oiHmENVCSkHhxDV85Dkm7JYR/czMCBeoM87WilTdSg==";
      };
    };
    "lodash-4.17.10" = {
      name = "lodash";
      packageName = "lodash";
      version = "4.17.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash/-/lodash-4.17.10.tgz";
        sha512 = "UejweD1pDoXu+AD825lWwp4ZGtSwgnpZxb3JDViD7StjQz+Nb/6l093lx4OQ0foGWNRoc19mWy7BzL+UAK2iVg==";
      };
    };
    "logform-1.9.1" = {
      name = "logform";
      packageName = "logform";
      version = "1.9.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/logform/-/logform-1.9.1.tgz";
        sha512 = "ZHrZE8VSf7K3xKxJiQ1aoTBp2yK+cEbFcgarsjzI3nt3nE/3O0heNSppoOQMUJVMZo/xiVwCxiXIabaZApsKNQ==";
      };
    };
    "minimist-1.2.0" = {
      name = "minimist";
      packageName = "minimist";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimist/-/minimist-1.2.0.tgz";
        sha1 = "a35008b20f41383eec1fb914f4cd5df79a264284";
      };
    };
    "ms-2.1.1" = {
      name = "ms";
      packageName = "ms";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ms/-/ms-2.1.1.tgz";
        sha512 = "tgp+dl5cGk28utYktBsrFqA7HKgrhgPsg6Z/EfhWI4gl1Hwq8B/GmY/0oXZ6nF8hDVesS/FpnYaD/kOWhYQvyg==";
      };
    };
    "node-uuid-1.4.8" = {
      name = "node-uuid";
      packageName = "node-uuid";
      version = "1.4.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/node-uuid/-/node-uuid-1.4.8.tgz";
        sha1 = "b040eb0923968afabf8d32fb1f17f1167fdab907";
      };
    };
    "one-time-0.0.4" = {
      name = "one-time";
      packageName = "one-time";
      version = "0.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/one-time/-/one-time-0.0.4.tgz";
        sha1 = "f8cdf77884826fe4dff93e3a9cc37b1e4480742e";
      };
    };
    "process-nextick-args-2.0.0" = {
      name = "process-nextick-args";
      packageName = "process-nextick-args";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/process-nextick-args/-/process-nextick-args-2.0.0.tgz";
        sha512 = "MtEC1TqN0EU5nephaJ4rAtThHtC86dNN9qCuEhtshvpVBkAW5ZO7BASN9REnF9eoXGcRub+pFuKEpOHE+HbEMw==";
      };
    };
    "readable-stream-1.1.14" = {
      name = "readable-stream";
      packageName = "readable-stream";
      version = "1.1.14";
      src = fetchurl {
        url = "https://registry.npmjs.org/readable-stream/-/readable-stream-1.1.14.tgz";
        sha1 = "7cf4c54ef648e3813084c636dd2079e166c081d9";
      };
    };
    "readable-stream-2.3.6" = {
      name = "readable-stream";
      packageName = "readable-stream";
      version = "2.3.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/readable-stream/-/readable-stream-2.3.6.tgz";
        sha512 = "tQtKA9WIAhBF3+VLAseyMqZeBjW0AHJoxOtYqSUZNJxauErmLbVm2FW1y+J/YA9dUrAC39ITejlZWhVIwawkKw==";
      };
    };
    "safe-buffer-5.0.1" = {
      name = "safe-buffer";
      packageName = "safe-buffer";
      version = "5.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/safe-buffer/-/safe-buffer-5.0.1.tgz";
        sha1 = "d263ca54696cd8a306b5ca6551e92de57918fbe7";
      };
    };
    "safe-buffer-5.1.2" = {
      name = "safe-buffer";
      packageName = "safe-buffer";
      version = "5.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/safe-buffer/-/safe-buffer-5.1.2.tgz";
        sha512 = "Gd2UZBJDkXlY7GbJxfsE8/nvKkUEU1G38c1siN6QP6a9PT9MmHB8GnpscSmMJSoF8LOIrt8ud/wPtojys4G6+g==";
      };
    };
    "simple-swizzle-0.2.2" = {
      name = "simple-swizzle";
      packageName = "simple-swizzle";
      version = "0.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/simple-swizzle/-/simple-swizzle-0.2.2.tgz";
        sha1 = "a4da6b635ffcccca33f70d17cb92592de95e557a";
      };
    };
    "stack-trace-0.0.10" = {
      name = "stack-trace";
      packageName = "stack-trace";
      version = "0.0.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/stack-trace/-/stack-trace-0.0.10.tgz";
        sha1 = "547c70b347e8d32b4e108ea1a2a159e5fdde19c0";
      };
    };
    "string_decoder-0.10.31" = {
      name = "string_decoder";
      packageName = "string_decoder";
      version = "0.10.31";
      src = fetchurl {
        url = "https://registry.npmjs.org/string_decoder/-/string_decoder-0.10.31.tgz";
        sha1 = "62e203bc41766c6c28c9fc84301dab1c5310fa94";
      };
    };
    "string_decoder-1.1.1" = {
      name = "string_decoder";
      packageName = "string_decoder";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/string_decoder/-/string_decoder-1.1.1.tgz";
        sha512 = "n/ShnvDi6FHbbVfviro+WojiFzv+s8MPMHBczVePfUpDJLwoLT0ht1l4YwBCbi8pJAveEEdnkHyPyTP/mzRfwg==";
      };
    };
    "text-hex-1.0.0" = {
      name = "text-hex";
      packageName = "text-hex";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/text-hex/-/text-hex-1.0.0.tgz";
        sha512 = "uuVGNWzgJ4yhRaNSiubPY7OjISw4sw4E5Uv0wbjp+OzcbmVU/rsT8ujgcXJhn9ypzsgr5vlzpPqP+MBBKcGvbg==";
      };
    };
    "triple-beam-1.3.0" = {
      name = "triple-beam";
      packageName = "triple-beam";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/triple-beam/-/triple-beam-1.3.0.tgz";
        sha512 = "XrHUvV5HpdLmIj4uVMxHggLbFSZYIn7HEWsqePZcI50pco+MPqJ50wMGY794X7AOOhxOBAjbkqfAbEe/QMp2Lw==";
      };
    };
    "ultron-1.1.1" = {
      name = "ultron";
      packageName = "ultron";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ultron/-/ultron-1.1.1.tgz";
        sha512 = "UIEXBNeYmKptWH6z8ZnqTeS8fV74zG0/eRU9VGkpzz+LIJNs8W/zM/L+7ctCkRrgbNnnR0xxw4bKOr0cW0N0Og==";
      };
    };
    "util-deprecate-1.0.2" = {
      name = "util-deprecate";
      packageName = "util-deprecate";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/util-deprecate/-/util-deprecate-1.0.2.tgz";
        sha1 = "450d4dc9fa70de732762fbd2d4a28981419a0ccf";
      };
    };
    "winston-3.0.0" = {
      name = "winston";
      packageName = "winston";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/winston/-/winston-3.0.0.tgz";
        sha512 = "7QyfOo1PM5zGL6qma6NIeQQMh71FBg/8fhkSAePqtf5YEi6t+UrPDcUuHhuuUasgso49ccvMEsmqr0GBG2qaMQ==";
      };
    };
    "winston-transport-4.2.0" = {
      name = "winston-transport";
      packageName = "winston-transport";
      version = "4.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/winston-transport/-/winston-transport-4.2.0.tgz";
        sha512 = "0R1bvFqxSlK/ZKTH86nymOuKv/cT1PQBMuDdA7k7f0S9fM44dNH6bXnuxwXPrN8lefJgtZq08BKdyZ0DZIy/rg==";
      };
    };
    "ws-2.3.1" = {
      name = "ws";
      packageName = "ws";
      version = "2.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ws/-/ws-2.3.1.tgz";
        sha1 = "6b94b3e447cb6a363f785eaf94af6359e8e81c80";
      };
    };
  };
  args = {
    name = "TaigaIO-Events";
    packageName = "TaigaIO-Events";
    version = "0.0.1";
    src = ./.;
    dependencies = [
      (sources."amqplib-0.5.2" // {
        dependencies = [
          sources."bluebird-3.5.1"
        ];
      })
      sources."async-2.6.1"
      sources."base64-url-1.3.3"
      sources."bitsyntax-0.0.4"
      sources."bluebird-2.11.0"
      sources."buffer-more-ints-0.0.2"
      sources."color-3.0.0"
      sources."color-convert-1.9.2"
      sources."color-name-1.1.1"
      sources."color-string-1.5.3"
      sources."colornames-1.1.1"
      sources."colors-1.3.1"
      sources."colorspace-1.1.1"
      sources."core-util-is-1.0.2"
      sources."diagnostics-1.1.1"
      sources."enabled-1.0.2"
      sources."env-variable-0.0.4"
      sources."fast-safe-stringify-2.0.5"
      sources."fecha-2.3.3"
      sources."inherits-2.0.3"
      sources."is-arrayish-0.3.2"
      sources."is-stream-1.1.0"
      sources."isarray-0.0.1"
      sources."kuler-1.0.0"
      sources."lodash-4.17.10"
      sources."logform-1.9.1"
      sources."minimist-1.2.0"
      sources."ms-2.1.1"
      sources."node-uuid-1.4.8"
      sources."one-time-0.0.4"
      sources."process-nextick-args-2.0.0"
      sources."readable-stream-1.1.14"
      sources."safe-buffer-5.1.2"
      sources."simple-swizzle-0.2.2"
      sources."stack-trace-0.0.10"
      sources."string_decoder-0.10.31"
      sources."text-hex-1.0.0"
      sources."triple-beam-1.3.0"
      sources."ultron-1.1.1"
      sources."util-deprecate-1.0.2"
      (sources."winston-3.0.0" // {
        dependencies = [
          sources."isarray-1.0.0"
          sources."readable-stream-2.3.6"
          sources."string_decoder-1.1.1"
        ];
      })
      (sources."winston-transport-4.2.0" // {
        dependencies = [
          sources."isarray-1.0.0"
          sources."readable-stream-2.3.6"
          sources."string_decoder-1.1.1"
        ];
      })
      (sources."ws-2.3.1" // {
        dependencies = [
          sources."safe-buffer-5.0.1"
        ];
      })
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "Taiga project management system (events)";
      license = "AGPL-3.0";
    };
    production = true;
    bypassCache = false;
  };
in
{
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
}